### ISSUE TITLE
Parsing suggestions for various devices

### ISSUE THREAD

**Issue by benbeckingsale** [nielsbasjes/yauaa#210]
Hi Niels, I have found a few prevalent useragents whose parsings could potentially be improved. I have detailed them below along with test cases. Would you be able to guide me on how best to add these to your library?

### First-Gen Amazon Echos
    Echo/1.0(APNG)

UAs from these devices are being classified as ‘Unknown’ in the device fields. Is it possible to update the matching as below?

    DeviceClass: Unknown  -->  Voice
    DeviceBrand: Unknown  -->  Amazon
    DeviceName:  Unknown  -->  Amazon Echo

Are you able to parse 1.0 as the Device Version?

### Sonos Speakers
    Linux UPnP/1.0 Sonos/53.3-71050 (ZPS1)
    Linux UPnP/1.0 Sonos/53.3-71050 (ZPS12)
    Linux UPnP/1.0 Sonos/53.3-71050 (ZP120)

UAs like these are also being classified as ‘Unknown’ in the device fields. I'm confident that `(ZPS1)` refers to the device model. Could you update the matching so that:

    DeviceBrand: Unknown  -->  Sonos
    DeviceName:  Unknown  -->  Sonos ZPS1

Speakers like this don’t seem to fit anywhere in YAUAA’s range of device classes. Would you consider introducing a dedicated class, such as ‘Smart Speaker’ for this kind of device?

### Playstation 3 Consoles
    PS3Application libhttp/4.8.5-000 (CellOS)

These UAs are also being classified as ‘Unknown’ in the device fields. Could you update the matching so that:

    DeviceClass: Unknown  -->  Game Console
    DeviceBrand: Unknown  -->  Sony
    DeviceName:  Unknown  -->  Playstation 3
    OSName:      Unknown  -->  CellOS

### Spotify Mobile App
    (1) Spotify/8.5.33 Android/28 (SM-G950F)
        Spotify/8.5.33 Android/29 (Pixel 3a)
    (2) Spotify/112000510 Win32/0 (PC laptop)
    (3) Spotify/8.5.33 iOS/13.1.3 (iPhone11,8)

UAs from the Android Spotify app `(1)` are being parsed as:

    DeviceClass: Mobile
    DeviceBrand: Unknown
    DeviceName:  Android Mobile
    AgentClass:  Browser
    AgentName:   Stock Android Browser

Similarly, with Windows `(2)`:

    DeviceClass: Unknown
    DeviceBrand: Unknown
    DeviceName:  Unknown
    AgentName:   Spotify

However, equivalent UAs from iOS devices `(3)` are parsed successfully as:

    DeviceClass: (Phone|Tablet)
    DeviceBrand: Apple
    DeviceName:  Apple (iPhone|iPad)
    AgentClass:  Special
    AgentName:   Spotify

I also noticed that the device name is usually found at the end of the Spotify UA (e.g. SM-G950F). Is it possible to parse this into `Device Name`?

Altogether, the ideal output for UA `(1)` would be:

    DeviceClass: Mobile
    DeviceBrand: Unknown                --> Samsung / Google
    DeviceName:  Android Mobile         --> Samsung SM-G950F / Google Pixel 3a
    AgentClass:  Browser                --> Special
    AgentName:   Stock Android Browser  --> Spotify

and for UA `(2)`

    DeviceClass: Unknown  -->  Desktop
    DeviceBrand: Unknown
    DeviceName:  Unknown
    OSName:      Unknown  -->  Windows
    AgentName:   Spotify  -->  Spotify  

## Test cases

1. Echo useragents
```
- test:
    input:
      user_agent_string: 'Echo/1.0(APNG)'
    expected:
      DeviceClass                          : 'Voice'
      DeviceName                           : 'Amazon Echo'
      DeviceBrand                          : 'Amazon'
      OperatingSystemClass                 : 'Mobile'
      OperatingSystemName                  : 'FireOS'
      OperatingSystemVersion               : '??'
      OperatingSystemVersionMajor          : '??'
      OperatingSystemNameVersion           : 'FireOS ??'
      OperatingSystemNameVersionMajor      : 'FireOS ??'
      OperatingSystemVersionBuild          : '??'
      LayoutEngineClass                    : 'Unknown'
      LayoutEdngineName                    : 'Unknown'
      LayoutEngineVersion                  : '??'
      LayoutEngineVersionMajor             : '??'
      LayoutEngineNameVersion              : 'Unknown ??'
      LayoutEngineNameVersionMajor         : 'Unknown ??'
      AgentClass                           : 'Special'
      AgentName                            : 'Echo'
      AgentVersion                         : '1.0'
      AgentVersionMajor                    : '1'
      AgentNameVersion                     : 'Echo 1.0'
      AgentNameVersionMajor                : 'Echo 1'
```

2. Sonos useragents
```
- test:
    input:
      user_agent_string: 'Linux UPnP/1.0 Sonos/53.3-71050 (ZPS1)'
    expected:
      DeviceClass: 'Smart Speaker'
      DeviceName: 'Sonos ZPS1'
      DeviceBrand: 'Sonos'
      OperatingSystemClass: 'Embedded'
      OperatingSystemName: 'Unknown'
      OperatingSystemVersion: '??'
      OperatingSystemVersionMajor: '??'
      OperatingSystemNameVersion: 'Unknown ??'
      OperatingSystemNameVersionMajor: 'Unknown ??'
      OperatingSystemVersionBuild: '??'
      LayoutEngineClass: 'Unknown'
      LayoutEngineName: 'Unknown'
      LayoutEngineVersion: '??'
      LayoutEngineVersionMajor: '??'
      LayoutEngineNameVersion: 'Unknown ??'
      LayoutEngineNameVersionMajor: 'Unknown ??'
      AgentClass: 'Special'
      AgentName: 'Linux UPnP'
      AgentVersion: '1.0'
      AgentVersionMajor: '1'
      AgentNameVersion: 'Linux UPnP 1.0'
      AgentNameVersionMajor: 'Linux UPnP 1'
```

3. Playstation 3 useragents
```
- test:
  input:
    user_agent_string:'PS3Application libhttp/4.8.5-000 (CellOS)'
  expected:
    DeviceClass: 'Game Console'
    DeviceName: 'Sony PlayStation 3'
    DeviceBrand: 'Sony'
    DeviceVersion: 'Unknown ??'
    OperatingSystemClass: 'Game Console'
    OperatingSystemName: 'CellOS'
    OperatingSystemVersion: '??'
    OperatingSystemVersionMajor: '??'
    OperatingSystemNameVersion: 'CellOS ??'
    OperatingSystemNameVersionMajor: 'CellOS ??'
    LayoutEngineClass: 'Unknown'
    LayoutEngineName: 'Unknown'
    LayoutEngineVersion: '??'
    LayoutEngineVersionMajor: '??'
    LayoutEngineNameVersion: 'Unknown ??'
    LayoutEngineNameVersionMajor: 'Unknown ??'
    AgentClass: 'Special'
    AgentName: 'PS3Application libhttp'
    AgentVersion: '4.8.5-000'
    AgentVersionMajor: '4'
    AgentNameVersion: 'PS3Applicationlibhttp 4.8.5-000'
    AgentNameVersionMajor: 'PS3Applicationlibhttp 4'
```

4. Spotify useragents
    (I inferred Android 9.0 from `/28` according to https://en.wikipedia.org/wiki/Android_version_history#Android_9_Pie_(API_28)).
```
- test:
  input:
    user_agent_string: 'Spotify/8.5.33 Android/28 (SM-G950F)'
  expected:
    DeviceClass: 'Phone'
    DeviceName: 'Samsung SM-G950F'
    DeviceBrand: 'Samsung'
    OperatingSystemClass: 'Mobile'
    OperatingSystemName: 'Android'
    OperatingSystemVersion: '9'
    OperatingSystemVersionMajor: '9'
    OperatingSystemNameVersion: 'Android 9'
    OperatingSystemNameVersionMajor: 'Android 9'
    OperatingSystemVersionBuild: 'Unknown'
    LayoutEngineClass: 'Unknown'
    LayoutEngineName: 'Unknown'
    LayoutEngineVersion: '??'
    LayoutEngineVersionMajor: '??'
    LayoutEngineNameVersion: 'UCBrowser U3 0.8.0'
    LayoutEngineNameVersionMajor: 'UCBrowser U3 0'
    AgentClass: 'Special'
    AgentName: 'Spotify'
    AgentVersion: '8.5.33'
    AgentVersionMajor: '8'
    AgentNameVersion: 'Spotify 8.5.33'
    AgentNameVersionMajor: 'Spotify 8'

- test:
  input:
    user_agent_string: 'Spotify/8.5.33 Android/29 (Pixel 3a)'
  expected:
    DeviceClass: 'Phone'
    DeviceName: 'Google Pixel 3a'
    DeviceBrand: 'Google'
    OperatingSystemClass: 'Mobile'
    OperatingSystemName: 'Android'
    OperatingSystemVersion: '10'
    OperatingSystemVersionMajor: '10'
    OperatingSystemNameVersion: 'Android 10'
    OperatingSystemNameVersionMajor: 'Android 10'
    OperatingSystemVersionBuild: 'Unknown'
    LayoutEngineClass: 'Unknown'
    LayoutEngineName: 'Unknown'
    LayoutEngineVersion: '??'
    LayoutEngineVersionMajor: '??'
    LayoutEngineNameVersion: 'UCBrowser U3 0.8.0'
    LayoutEngineNameVersionMajor: 'UCBrowser U3 0'
    AgentClass: 'Special'
    AgentName: 'Spotify'
    AgentVersion: '8.5.33'
    AgentVersionMajor: '8'
    AgentNameVersion: 'Spotify 8.5.33'
    AgentNameVersionMajor: 'Spotify 8'

- test:
  input:
    user_agent_string: 'Spotify/112000510 Win32/0 (PC laptop)'
  expected:
    DeviceClass: 'Desktop'
    DeviceName: 'Unknown'
    DeviceBrand: 'Unknown'
    OperatingSystemClass: 'Desktop'
    OperatingSystemName: 'Windows'
    OperatingSystemVersion: '??'
    OperatingSystemVersionMajor: '??'
    OperatingSystemNameVersion: 'Windows ??'
    OperatingSystemNameVersionMajor: 'Windows ??'
    OperatingSystemVersionBuild: 'Unknown'
    LayoutEngineClass: 'Unknown'
    LayoutEngineName: 'Unknown'
    LayoutEngineVersion: '??'
    LayoutEngineVersionMajor: '??'
    LayoutEngineNameVersion: 'UCBrowser U3 0.8.0'
    LayoutEngineNameVersionMajor: 'UCBrowser U3 0'
    AgentClass: 'Special'
    AgentName: 'Spotify'
    AgentVersion: '112000510'
    AgentVersionMajor: '112000510'
    AgentNameVersion: 'Spotify 112000510'
    AgentNameVersionMajor: 'Spotify 112000510'
```
